services:
  hyshare:
    image: ghcr.io/floogulinc/hyshare:latest
    env_file: hyshare.env
    ports:
      - 3333:3333
    #environment:
    #  HYSHARE_PORT: 3333
    #  HYSHARE_HYDRUS_API_URL: 
    #  HYSHARE_HYDRUS_API_KEY: 
